# Generated by Django 2.1.4 on 2019-01-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190126_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='p_menu_id',
        ),
        migrations.AddField(
            model_name='permission',
            name='sub_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='rbac.Permission', verbose_name='所属子菜单'),
        ),
    ]
